version: '2'
services:
  php:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    environment:
      PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
      PHP_IDE_CONFIG: serverName=localhost
      WAIT_HOSTS: db:3306, db-test:3306
    ports:
      - '8000:80'
    networks:
      - db
    depends_on:
      - db
      - db-test
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: example
    ports:
      - ${MYSQL_PORT_EXTERNAL:-3301}:3306
    networks:
      - db
  db-test:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: example
    ports:
      - ${MYSQL_PORT_EXTERNAL_TEST:-3302}:3306
    networks:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_DB_NAME: ${MYSQL_DATABASE}
    networks:
      - db
networks:
  db: