version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    environment:
      PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
      PHP_IDE_CONFIG: serverName=localhost
    ports:
      - '8000:80'
    networks:
      - db
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: example
    ports:
      - ${MYSQL_PORT_EXTERNAL:-3301}:3306
    networks:
      - db
networks:
  db: